go:
    # Whenever the Go version is updated here, .travis.yml and
    # .circle/config.yml should also be updated if in use.
    version: 1.12
repository:
    path: github.com/prometheus/prombench
build:
    binaries:
        - name: ./prombench/prombench
          path: ./prombench/cmd/prombench
        - name: ./prombench/scaler
          path: ./prombench/tools/scaler
        - name: ./prombench/fake-webserver
          path: ./prombench/tools/fake-webserver
        - name: ./prombench/commentMonitor
          path: ./prombench/tools/commentMonitor
        - name: ./prombench/amGithubNotifier
          path: ./prombench/tools/amGithubNotifier
    flags: -a -tags netgo

crossbuild:
    platforms:
        - linux/amd64
