plugins:
  testpromorg/prometheus:
  - lgtm
  - wip
  testpromorg/prombench:
  - wip
  - config-updater

config_updater:
  maps:
    config/prow/config.yaml:
      name: prow-config
    config/prow/plugins.yaml:
      name: prow-config
    config/prow/jobs/**/*.yaml:
      name: job-config

external_plugins:
  testpromorg/prometheus:
  - name: prombenchmark-extplugin
    #endpoint: http://prombenchmark-extplugin
    events:
    - issue_comment
