plugins:
  prometheus/prometheus:
  - lgtm
  - wip
  #- prombenchbenchmark
  prometheus/prombench:
  - wip
  - config-updater

config_updater:
  maps:
    config/prow/config.yaml:
      name: prow-config
    config/prow/plugins.yaml:
      name: prow-config
    config/prow/jobs/**/*.yaml:
      name: job-config

external_plugins:
  prometheus/prombench:
  - name: prombenchmark-extplugin
    endpoint: http://prombenchmark-extplugin:8080
    events:
    - pull_request
