apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prombench-test-{{ .PR_NUMBER }}
  labels:
    app: prombench-test-{{ .PR_NUMBER }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prombench-test-{{ .PR_NUMBER }}
  template:
    metadata:
      labels:
        app: prombench-test-{{ .PR_NUMBER }}
        last_commit: {{ .LAST_COMMIT }}
    spec:
      containers:
      - name: prombench-test-{{ .PR_NUMBER }}
        image: docker.io/prombench/prombench:2.0.2
        imagePullPolicy: Always
        env:
          - name: SHELL_COMMAND
            value: "supervisorctl start deploy"
          - name: PROJECT_ID
            value: "{{ .PROJECT_ID }}"
          - name: ZONE
            value: "{{ .ZONE }}"
          - name: CLUSTER_NAME
            value: "{{ .CLUSTER_NAME }}"
          - name: RELEASE
            value: "{{ .RELEASE }}"
          - name: PR_NUMBER
            value: "{{ .PR_NUMBER }}"
          - name: DOMAIN_NAME
            value: "{{ .DOMAIN_NAME }}"
          - name: TEST_INFRA_REPO
            value: "{{ .TEST_INFRA_REPO }}"
          - name: GITHUB_ORG
            value: "{{ .GITHUB_ORG }}"
          - name: GITHUB_REPO
            value: "{{ .GITHUB_REPO }}"
        lifecycle:
          preStop:
            exec:
              command:
              - "sh"
              - "-c"
              - "supervisorctl start clean && sleep 99999999"
        readinessProbe:
          exec:
            command:
            # successful cat /tmp/READY marks the pod ready
            - cat
            - /tmp/READY
          # Period and Threshold combined should be less than pkg/provider/globalRetryTime.
          periodSeconds: 5
          failureThreshold: 1
        volumeMounts:
        - name: serviceaccount
          mountPath: /etc/serviceaccount/
          readOnly: true
      volumes:
        - name: serviceaccount
          secret:
            secretName: service-account
      terminationGracePeriodSeconds: 900 # 15 mins
      nodeSelector:
        cloud.google.com/gke-nodepool: prow

