global:
  scrape_interval: 5s
scrape_configs:

- job_name: kubelet
  scheme: https
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    insecure_skip_verify: true
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

  kubernetes_sd_configs:
  - role: node

  relabel_configs:
  - action: labelmap
    regex: __meta_kubernetes_node_label_(.+)
  - target_label: __address__
    replacement: kubernetes.default.svc:443
  - source_labels: [__meta_kubernetes_node_name]
    regex: (.+)
    target_label: __metrics_path__
    replacement: /api/v1/nodes/${1}/proxy/metrics

- job_name: cadvisor
  scheme: https
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    insecure_skip_verify: true
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

  kubernetes_sd_configs:
  - role: node

  relabel_configs:
  - action: labelmap
    regex: __meta_kubernetes_node_label_(.+)
  - target_label: __address__
    replacement: kubernetes.default.svc:443
  - source_labels: [__meta_kubernetes_node_name]
    regex: (.+)
    target_label: __metrics_path__
    replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor

- job_name: endpoints
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    insecure_skip_verify: true
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

  kubernetes_sd_configs:
  - role: endpoints

  relabel_configs:
  - action: keep
    source_labels: [__meta_kubernetes_service_label_app]
    regex: prometheus|prometheus-meta|node-exporter|loadgen-querier
  - action: replace
    source_labels: [__meta_kubernetes_service_label_app]
    target_label: job
  - action: replace
    source_labels: [__meta_kubernetes_namespace]
    target_label: namespace
  - action: replace
    source_labels: [__meta_kubernetes_service_label_prometheus]
    target_label: prometheus
  - action: replace
    source_labels: [__meta_kubernetes_pod_node_name]
    target_label: nodeName
  - action: replace
    source_labels: [__meta_kubernetes_pod_label_node]
    target_label: node
  - action: replace
    source_labels: [__meta_kubernetes_namespace,__meta_kubernetes_service_label_prometheus]
    regex: prombench-(\d+);test-pr-\d+
    target_label: __metrics_path__
    replacement: /${1}/prometheus-pr/metrics
  - action: replace
    source_labels: [__meta_kubernetes_namespace,__meta_kubernetes_service_label_prometheus]
    regex: prombench-(\d+);test-(?:master|v.+)
    target_label: __metrics_path__
    replacement: /${1}/prometheus-release/metrics
  - action: replace
    source_labels: [__meta_kubernetes_namespace,__meta_kubernetes_service_label_prometheus]
    regex: default;meta
    target_label: __metrics_path__
    replacement: /prometheus-meta/metrics
