apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      group_by: ['alertname', 'namespace']
      group_wait: 1m
      group_interval: 5m
      repeat_interval: 4h
      receiver: amgh-bridge
      match:
        job: node-exporter

    receivers:
    - name: amgh-bridge
      webhook_configs:
      - send_resolved: false
        url: 'http://amgh/hook'