apiVersion: apps/v1
kind: Deployment
metadata:
  name: amGithubNotifier
  labels:
    app: amGithubNotifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amGithubNotifier
  template:
    metadata:
      labels:
        app: amGithubNotifier
    spec:
      containers:
      - name: amGithubNotifier
        image: docker.io/prombench/amGithubNotifier:0.0.1
        args:
        - "--org=prometheus"
        - "--repo=prometheus"
        volumeMounts:
        - name: oauth
          mountPath: /etc/github
          readOnly: true
        ports:
        - name: amGithubNotifier-webhook
          containerPort: 8080
      volumes:
      - name: oauth
        secret:
          secretName: oauth-token
      terminationGracePeriodSeconds: 300
      nodeSelector:
        cloud.google.com/gke-nodepool: prow
---
apiVersion: v1
kind: Service
metadata:
  name: amGithubNotifier
  labels:
    app: amGithubNotifier
spec:
  type: ClusterIP
  ports:
  - name: amGithubNotifier-webhook
    port: 80
    targetPort: amGithubNotifier-webhook
  selector:
    app: amGithubNotifier