apiVersion: v1
kind: ConfigMap
metadata:
  name: amgithubnotifier-templates
data:
  default: |
    'Alertmanager URL: {{ "{{" }} .Data.ExternalURL {{ "}}" }}'
  benchmarkTestsRunning: |
    Benchmark running for more than three days. Please consider stopping the benchmark
    or silencing this alert.

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amgithubnotifier
  labels:
    app: amgithubnotifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amgithubnotifier
  template:
    metadata:
      labels:
        app: amgithubnotifier
    spec:
      containers:
      - name: amgithubnotifier
        image: docker.io/prombench/amgithubnotifier:0.0.1
        args:
        - "--org={{ .GITHUB_ORG }}"
        - "--repo={{ .GITHUB_REPO }}"
        - "--template-dir-path=/etc/amgithubnotifier/templates"
        volumeMounts:
        - name: oauth
          mountPath: /etc/github
          readOnly: true
        - name: amgithubnotifier-templates
          mountPath: /etc/amgithubnotifier/templates
        ports:
        - name: amgh-port
          containerPort: 8080
      volumes:
      - name: oauth
        secret:
          secretName: oauth-token
      - name: amgithubnotifier-templates
        configMap:
          name: amgithubnotifier-templates
      terminationGracePeriodSeconds: 300
      nodeSelector:
        cloud.google.com/gke-nodepool: prow
---
apiVersion: v1
kind: Service
metadata:
  name: amgithubnotifier
  labels:
    app: amgithubnotifier
spec:
  type: ClusterIP
  ports:
  - name: amgh-port
    port: 80
    targetPort: amgh-port
  selector:
    app: amgithubnotifier
