apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-loadgen-restarter
  namespace: prombench-{{ .PR_NUMBER }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgen-restarter
  template:
    metadata:
      namespace: prombench-{{ .PR_NUMBER }}
      labels:
        app: loadgen-restarter
    spec:
      serviceAccountName: loadgen-restarter
      containers:
      - name: prom-load-generator-restarter
        image: docker.io/geekodour/restarter:1.0.0
        imagePullPolicy: Always
        args:
        - "restart"
        - "-v"
        - "PR_NUMBER:{{ .PR_NUMBER }}"
      nodeSelector:
        cloud.google.com/gke-nodepool: nodes-{{ .PR_NUMBER }}
        isolation: none