apiVersion: apps/v1
kind: Deployment
metadata:
  name: prombenchmark-extplugin
  labels:
    app: prombenchmark-extplugin
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: prombenchmark-extplugin
  template:
    metadata:
      labels:
        app: prombenchmark-extplugin
    spec:
      serviceAccountName: "hook"
      terminationGracePeriodSeconds: 180
      containers:
      - name: prombenchmark-extplugin
        image: docker.io/prombenchgeekodour/prombenchmark:0.0.1
        imagePullPolicy: Always
        args:
        - --project-id={{ .PROJECT_ID }}
        - --cluster-name={{ .CLUSTER_NAME }}
        - --domain-name={{ .DOMAIN_NAME }}
        - --zone={{ .ZONE }}
        ports:
          - name: http
            containerPort: 8080
        volumeMounts:
        - name: hmac
          mountPath: /etc/webhook
          readOnly: true
        - name: oauth
          mountPath: /etc/github
          readOnly: true
        - name: job-config
          mountPath: /etc/job-config
          readOnly: true
      volumes:
      - name: hmac
        secret:
          secretName: hmac-token
      - name: oauth
        secret:
          secretName: oauth-token
      - name: job-config
        configMap:
          name: job-config
      nodeSelector:
        cloud.google.com/gke-nodepool: prow

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prombenchmark-extplugin
  name: prombenchmark-extplugin
spec:
  selector:
    app: prombenchmark-extplugin
  ports:
  - name: main
    port: 8080
  type: NodePort
