apiVersion: v1
kind: ConfigMap
metadata:
  name: plugins
data:
  plugins.yaml: |
    triggers:
    - repos:
      - {{ .GITHUB_ORG }}/prometheus
      - {{ .GITHUB_ORG }}/prombench
      trusted_org: {{ .GITHUB_ORG }}
      only_org_members: true

      #external_plugins:
      #  prombench:
      #  - name: benchmark
      #    events:
      #    - pull_request

    config_updater:
      maps:
        manifests/prow/config_configmap.yaml:
          name: config
        manifests/prow/plugins_configmap.yaml:
          name: plugins
        manifests/prow/jobs/**/*.yaml:
          name: job-config
          gzip: true

    plugins:
      {{ .GITHUB_ORG }}/prometheus:
      - lgtm
      - wip
      {{ .GITHUB_ORG }}/prombench:
      - wip
      - config-updater # only {{ .GITHUB_ORG }}/prombench should be running this plugin
